---
swagger: "2.0"
basePath: "/response/SimpleWS"
info:
  description: "Simple API"
  title: "Simple"
  version: "1.0"
host: "192.168.50.13:7800"
consumes:
- "application/json"
produces:
- "appliction/json"
definitions:
  input:
    properties:
      input:
        type: "string"
  output:
    properties:
      output:
        type: "string"
paths:
  /getByInput:
    post:
      operationId: "getByInput"
      parameters:
      - name: "body"
        in: "body"
        schema:
          $ref: "#/definitions/input"
      responses:
        "200":
          description: "OK response"
          schema:
            $ref: "#/definitions/output"
      description: "simple string"
